### ISSUE TITLE
Bump timfel-krb5-auth version to 0.8.3

### ISSUE THREAD

**Issue by s1341** [jgraichen/omniauth-kerberos#1]
Hi,

Can you please bump your dependency on timfel-krb5-auth to the latest version? There has been a patch which resolves an issue when building timfel-krb5-auth on some systems. Version 0.8.3 resolves this issue.

Thanks!

**Comment by jgraichen** [comment]
omniauth-kerberos specifies `~> 0.8` which means `>= 0.8, < 1.0` that covers `0.8.3`. A quick test installing omniauth-kerberos via `gem` in a clean set also installed `timfel-krb5-auth` in version `0.8.3`.

When using bundler try running `bundle update timfel-krb5-auth`.
